### ISSUE TITLE
What is termp?

### ISSUE THREAD

**Issue by atgreen** [vindarel/lftp-wrapper#2]
What is the `termp` package that this depends on?

**Comment by vindarel** [comment]
Hello Anthony, it's this little ("trivial") package:

https://github.com/vindarel/termp/

> Are we running inside a real or a dumb terminal window?

It checks the "TERM" env var.

**Comment by atgreen** [comment]
Got it!  It's in ocicl now.

**Comment by vindarel** [comment]
nice, thanks.

Hats off for the work on ocicl!

**Comment by vindarel** [comment]
your additions are not automatically reflected in https://github.com/ocicl/request-system-additions-here ?

**Comment by atgreen** [comment]
I don't update that as regularly as I should.  I should automate that.
It's updated now.
